/bridge_rbcar_controller_node:
  ros__parameters:
    sub_topic: "command"
    ros_1_server_ip: "localhost"
    ros_1_server_port: 8888

    pub_topic_1: "speed"
    ros_2_server_port_1: 8889

    pub_topic_2: "imu"
    ros_2_server_port_2: 8890

    pub_topic_3: "steering"
    ros_2_server_port_3: 8891

    Hz: 100